### PR TITLE
Updated recommended type to c4.large, added t2 types

### PR DESCRIPTION
**Pull request by emaildano**

### CODE REVIEW

**Comment by hideokamoto** [comment]
Thanks !
But HHVM AMI does not support t2 instances.
Please update params to remove it.

**Comment by emaildano** [comment]
@hideokamoto Does HHVM not support T2 due to memory limits or is there another reason?

**Comment by hideokamoto** [comment]
For now, HHVM AMI allows only t2.large.
https://aws.amazon.com/marketplace/pp/B00V5JYXTO

If you want to know the reason, please ask @wokamoto or @megumi.

**Comment by hideokamoto** [comment]
And unfortunately, we don't have to update `json/`files directory.
These code managed by `kumogata` https://github.com/kumogata/kumogata .
We have to update kumogata template files similar to Saas or Less.

**Pull request merged**
